# Generated by Django 5.0.3 on 2024-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_expiredate_alter_poll_questiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceText',
            field=models.CharField(blank=True, db_column='choiceText', max_length=100),
        ),
    ]
