# Generated by Django 5.0.3 on 2024-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_choicetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='expireDate',
            field=models.DateField(db_column='expireDate', null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pollImage',
            field=models.ImageField(db_column='pollImage', max_length=50, upload_to='image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='questionText',
            field=models.CharField(db_column='questionText', max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
